### ISSUE TITLE
Volume options are set repeatedly

### ISSUE THREAD

**Issue by deubert-it** [voxpupuli/puppet-gluster#269]
```
gluster::volumes:
  'staging':
    force: true
    replica: 3
    bricks:
      - 'acme-stage-gluster01:/export/brick1/brick'
      - 'acme-stage-gluster02:/export/brick1/brick'
      - 'acme-stage-gluster03:/export/brick1/brick'
    options:
      - 'nfs.disable: true'
      - 'features.cache-invalidation: on'
      - 'features.cache-invalidation-timeout: 600'
      - 'performance.stat-prefetch: on'
      - 'performance.cache-invalidation: on'
      - 'performance.cache-max-file-size: 1MB'
      - 'performance.cache-size: 128MB'
      - 'performance.parallel-readdir: on'
      - 'performance.io-thread-count: 32'
      - 'performance.quick-read: on'
      - 'network.inode-lru-limit: 90000'
```

This will always end in the same for every agent run:

```
Notice: /Stage[main]/Gluster/Gluster::Volume[staging]/Gluster::Volume::Option[staging:features.cache-invalidation-timeout]/Exec[gluster option staging features.cache-invalidation-timeout 600]/returns: executed successfully (corrective)
Notice: /Stage[main]/Gluster/Gluster::Volume[staging]/Gluster::Volume::Option[staging:features.cache-invalidation]/Exec[gluster option staging features.cache-invalidation on]/returns: executed successfully (corrective)
Notice: /Stage[main]/Gluster/Gluster::Volume[staging]/Gluster::Volume::Option[staging:performance.cache-invalidation]/Exec[gluster option staging performance.cache-invalidation on]/returns: executed successfully (corrective)
Notice: /Stage[main]/Gluster/Gluster::Volume[staging]/Gluster::Volume::Option[staging:performance.parallel-readdir]/Exec[gluster option staging performance.parallel-readdir on]/returns: executed successfully (corrective)
Notice: /Stage[main]/Gluster/Gluster::Volume[staging]/Gluster::Volume::Option[staging:performance.quick-read]/Exec[gluster option staging performance.quick-read on]/returns: executed successfully (corrective)
Notice: /Stage[main]/Gluster/Gluster::Volume[staging]/Gluster::Volume::Option[staging:performance.stat-prefetch]/Exec[gluster option staging performance.stat-prefetch on]/returns: executed successfully (corrective)
```

However, when checking the gluster volume options manually:
```
gluster volume get staging performance.stat-prefetch
Option                                   Value                                  
------                                   -----                                  
performance.stat-prefetch                true
```

The gluster documentation also seems to rather talk about on|off vs true/false. It seems that there is some conversion done from "on" to "true" somewhere in the module.

The gluster volume is not restarting and the service is not interrupted, so the behaviour is not breaking functionality, however flooding logs and showing unneeded activity.

Environment

```
dpkg -l | grep gluster
ii  glusterfs-cli                    10.3-5                                  amd64        clustered file-system (cli package)
ii  glusterfs-client                 10.3-5                                  amd64        clustered file-system (client package)
ii  glusterfs-common                 10.3-5                                  amd64        GlusterFS common libraries and translator modules
ii  glusterfs-server                 10.3-5                                  amd64        clustered file-system (server package)
ii  libglusterd0:amd64               10.3-5                                  amd64        GlusterFS glusterd shared library
ii  libglusterfs0:amd64              10.3-5                                  amd64        GlusterFS shared library
```

```
cat /etc/debian_version 
12.10
```

Might be related to or fixed in https://github.com/voxpupuli/puppet-gluster/pull/196/files
