### ISSUE TITLE
module slow when setting options on volumes

### ISSUE THREAD

**Issue by sammcj** [voxpupuli/puppet-gluster#86]
At present, options are _very_ slow to apply to clusters using this module as it iterates (slowly) over each volume and takes a long time to set each setting.

```yaml
    pool_volumes:
      vol1:
        replica: 2
        brick_mountpoint: '/mnt/intpool01'
        options:
          - 'nfs.disable: true'
          - 'cluster.lookup-optimize: true'
          - 'cluster.readdir-optimize: true'
          - 'performance.cache-size: 768MB'
          - 'performance.io-cache: true'
          - 'performance.io-thread-count: 32'
          - 'performance.write-behind-window-size: 2MB'
          - 'performance.cache-refresh-timeout: 4'
          - 'server.event-threads: 8'
          - 'client.event-threads: 8'
          - 'diagnostics.brick-log-level: WARNING'
          - 'diagnostics.client-log-level: WARNING'

      vol2:
        replica: 2
        brick_mountpoint: '/mnt/intpool01'
        options:
          - 'nfs.disable: true'
          - 'cluster.lookup-optimize: true'
          - 'cluster.readdir-optimize: true'
          - 'performance.cache-size: 768MB'
          - 'performance.io-cache: true'
          - 'performance.io-thread-count: 32'
          - 'performance.write-behind-window-size: 2MB'
          - 'performance.cache-refresh-timeout: 4'
          - 'server.event-threads: 8'
          - 'client.event-threads: 8'
          - 'diagnostics.brick-log-level: WARNING'
          - 'diagnostics.client-log-level: WARNING'
```

**Comment by sammcj** [comment]
At present, options are passed in via the volume resource, which doesn't make much sense if they're options that have nothing to do with the volume but are instead global and results in duplication, for example:

```yaml
    pool_volumes:
      vol1:
        replica: 2
        brick_mountpoint: '/mnt/intpool01'
        options:
          - 'nfs.disable: true'
          - 'cluster.lookup-optimize: true'
          - 'cluster.readdir-optimize: true'
          - 'performance.cache-size: 768MB'
          - 'performance.io-cache: true'
          - 'performance.io-thread-count: 32'
          - 'performance.write-behind-window-size: 2MB'
          - 'performance.cache-refresh-timeout: 4'
          - 'server.event-threads: 8'
          - 'client.event-threads: 8'
          - 'diagnostics.brick-log-level: WARNING'
          - 'diagnostics.client-log-level: WARNING'

      vol2:
        replica: 2
        brick_mountpoint: '/mnt/intpool01'
        options:
          - 'nfs.disable: true'
          - 'cluster.lookup-optimize: true'
          - 'cluster.readdir-optimize: true'
          - 'performance.cache-size: 768MB'
          - 'performance.io-cache: true'
          - 'performance.io-thread-count: 32'
          - 'performance.write-behind-window-size: 2MB'
          - 'performance.cache-refresh-timeout: 4'
          - 'server.event-threads: 8'
          - 'client.event-threads: 8'
          - 'diagnostics.brick-log-level: WARNING'
          - 'diagnostics.client-log-level: WARNING'
```

Surely things like:

```yaml
          - 'cluster.lookup-optimize: true'
          - 'cluster.readdir-optimize: true'
```

Should be set as global options and not repeated for every volume?
